
name: tchat
description: A full-featured Flutter messaging app

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: 4.17.5
  firebase_storage: ^11.0.0
  image_picker: ^1.0.0
  firebase_messaging: ^14.0.0
  provider: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
